export const CONTENT_TYPE_SAVE = "CONTENT_TYPE_SAVE";
export const CONTENT_TYPE_LOAD = "CONTENT_TYPE_LOAD";
export const CONTENT_TYPE_ERROR = "CONTENT_TYPE_ERROR";
export const CONTENT_TYPE_DELETE_CONFIRM = "CONTENT_TYPE_DELETE_CONFIRM";
export const CONTENT_TYPE_DELETE_CANCEL = "CONTENT_TYPE_DELETE_CANCEL";
export const CONTENT_TYPE_DELETE_ASK_CONFIRMATION = "CONTENT_TYPE_DELETE_ASK_CONFIRMATION";
export const CONTENT_TYPE_FIELD_CHANGED = "CONTENT_TYPE_FIELD_CHANGED";
export const CONTENT_TYPE_LIST_LOAD = "CONTENT_TYPE_LIST_LOAD";