// <auto-generated />
using Komandir.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Komandir.Migrations
{
    [DbContext(typeof(KomandirDbContext))]
    [Migration("20200218154017_Create")]
    partial class Create
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("Komandir.Models.ContentType", b =>
                {
                    b.Property<int>("ContentTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ContentTypeID");

                    b.ToTable("ContentTypes");
                });

            modelBuilder.Entity("Komandir.Models.ContentTypeAttribute", b =>
                {
                    b.Property<int>("ContentTypeAttributeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContentTypeID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DataTypeID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ContentTypeAttributeID");

                    b.HasIndex("ContentTypeID");

                    b.HasIndex("DataTypeID");

                    b.ToTable("ContentTypeAttributes");
                });

            modelBuilder.Entity("Komandir.Models.ContentTypeAttributeEditor", b =>
                {
                    b.Property<int>("ContentTypeAttributeEditorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Component")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ContentTypeAttributeEditorID");

                    b.ToTable("ContentTypeAttributeEditors");
                });

            modelBuilder.Entity("Komandir.Models.DataType", b =>
                {
                    b.Property<int>("DataTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DataTypeID");

                    b.ToTable("DataTypes");
                });

            modelBuilder.Entity("Komandir.Models.ContentTypeAttribute", b =>
                {
                    b.HasOne("Komandir.Models.ContentType", "ContentType")
                        .WithMany("ContentTypeAttributes")
                        .HasForeignKey("ContentTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Komandir.Models.DataType", "DataType")
                        .WithMany()
                        .HasForeignKey("DataTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
