export const CONTENT_TYPE_DELETE_OK = "CONTENT_TYPE_DELETE_OK";
export const CONTENT_TYPE_DELETE_CANCEL = "CONTENT_TYPE_DELETE_CANCEL";
export const CONTENT_TYPE_DELETE_PROMPT = "CONTENT_TYPE_DELETE_PROMPT";
export const CONTENT_TYPE_LIST_LOAD = "CONTENT_TYPE_LIST_LOAD";

export const CONTENT_TYPE_ERROR = "CONTENT_TYPE_ERROR";
export const CONTENT_TYPE_FIELD_DELETE_PROMPT =
  "CONTENT_TYPE_FIELD_DELETE_PROMPT";
export const CONTENT_TYPE_FIELD_DELETE = "CONTENT_TYPE_FIELD_DELETE";

export const FORM_CHANGED = "FORM_CHANGED";
export const FORM_LOAD = "FORM_LOAD";
export const FORM_ERROR = "FORM_ERROR";
export const FORM_SAVE = "FORM_SAVE";
