export const CONTENT_TYPE_DELETE_OK = "CONTENT_TYPE_DELETE_OK";
export const CONTENT_TYPE_DELETE_CANCEL = "CONTENT_TYPE_DELETE_CANCEL";
export const CONTENT_TYPE_DELETE_PROMPT = "CONTENT_TYPE_DELETE_PROMPT";
export const CONTENT_TYPE_READ_LIST = "CONTENT_TYPE_READ_LIST";

export const CONTENT_TYPE_FIELD_DELETE_PROMPT = "CONTENT_TYPE_FIELD_DELETE_PROMPT";
export const CONTENT_TYPE_FIELD_EDIT_PROMPT = "CONTENT_TYPE_FIELD_EDIT_PROMPT";
export const CONTENT_TYPE_FIELD_DELETE = "CONTENT_TYPE_FIELD_DELETE";
export const CONTENT_TYPE_FIELD_CHANGE = "CONTENT_TYPE_FIELD_CHANGE";

export const CONTENT_TYPE_CHANGE = "CONTENT_TYPE_CHANGE";
export const CONTENT_TYPE_READ = "CONTENT_TYPE_READ";
export const CONTENT_TYPE_ERROR = "CONTENT_TYPE_ERROR";
export const CONTENT_TYPE_UPDATE = "CONTENT_TYPE_UPDATE";
